= {docname}
:autor: Diixo Diixo
:email: diixo.com@gmail.com
:version: 0.1
:date: 2015-11-20
:deliverystate: Draft 
:cpp: {basebackend@docbook:c++:cpp}

[options="header",cols="<12%,^15%,<20%,<53%"]
|====
| Revision | Date       | Author     | Description
| 0.1      | 2015-11-21 | Diixo      | Matrix chapter was added
|====

== Arbitrary camera

=== The Camera Transformation

The camera transformation is the transformation matrix that can be used to position and orient an object or a model in the scene that represents the camera. If you wanted to represent several cameras in the scene and you wanted to visualize where each camera was placed in the world, then this transformation would be used to transform the vertices of the model that represents the camera from object-space into world space. This is the same as a world-matrix or model-matrix that positions any model in the scene. This transformation should not be mistaken as the view matrix.  It cannot be used directly to transform vertices from world-space into view-space.

To compute the camera's transformation matrix is no different from computing the transformation matrix of any object placed in the scene.

If *R* represents the orientation of the camera, and *T* represents the translation of the camera in world space, then the camera's transform matrix *M* can be computed by multiplying the two matrices together.

*M* = *T* *** *R* 

*M_lookAt* = *M'* = *R'* *** *T'* 


=== The View Matrix

The view matrix on the other hand is used to transform vertices from world-space to view-space.  This matrix is usually concatenated together with the object's world matrix and the projection matrix so that vertices can be transformed from object-space directly to clip-space in the vertex program.

If *M* represents the object's world matrix (or model matrix), and *V* represents the view matrix, and *P* is the projection matrix, then the concatenated world (or model), view, projection can be represented by *MVP* simply by multiplying the three matrices together:

*MVP* = *P* *** *V* *** *M*

And a vertex *v* can be transformed to clip-space by multiplying by the combined matrix *MVP* :

*v'* *=* *MVP* *** *v*


View world representation is representation vector as in form:

*TransformedVector* = *TranslationMatrix* *** *RotationMatrix* *** *ScaleMatrix* *** *OriginalVector*;

=== Matrix representation

*World orientation representation*:
----
[ right.x, up.x, dir.x,  0 ]
[ right.y, up.y, dir.y,  0 ] = M_axis
[ right.z, up.z, dir.z,  0 ]
[       0,    0,     0,  1 ]
----

*Back rotation*:
----
M_axis * M_axis' = M(1)
----

----
[ right.x, right.y, right.z, 0 ]    
[ up.x,    up.y,    up.z,    0 ] = M_axis' = R' 
[ dir.x,   dir.y,   dir.z,   0 ]    
[ 0,       0,       0,       1 ] 
----

*World translation representation*:
----
[ 1, 0, 0, eye.x ]   
[ 0, 1, 0, eye.y ] = T = M_translation(eye)
[ 0, 0, 1, eye.z ]  
[ 0, 0, 0, 1     ]  
----

*Back translation*:
----
M_translation(eye) * M_translation(-eye) = M(1)
----

----
[ 1, 0, 0, -eye.x ]   
[ 0, 1, 0, -eye.y ] = T' = M_translation(-eye)
[ 0, 0, 1, -eye.z ]  
[ 0, 0, 0,  1     ]  
----

*Matrix world positioning representation*:

*M* = *T* *** *R*

----
[ 1, 0, 0, eye.x ]   [ right.x, up.x, dir.x,  0 ]   
[ 0, 1, 0, eye.y ] x [ right.y, up.y, dir.y,  0 ] =
[ 0, 0, 1, eye.z ]   [ right.z, up.z, dir.z,  0 ]   
[ 0, 0, 0, 1     ]   [       0,    0,     0,  1 ]   

   [ right.x, up.x, dir.x,  eye.x ]   
 = [ right.y, up.y, dir.y,  eye.y ]
   [ right.z, up.z, dir.z,  eye.z ]
   [       0,    0,     0,     1  ]
----

*Matrix lookAt representation*:

*M_lookAt* = *R'* *** *T'*

----
[ right.x, right.y, right.z, 0 ]   [ 1, 0, 0, -eye.x ]   
[ up.x,    up.y,    up.z,    0 ] x [ 0, 1, 0, -eye.y ] =
[ dir.x,   dir.y,   dir.z,   0 ]   [ 0, 0, 1, -eye.z ]  
[ 0,       0,       0,       1 ]   [ 0, 0, 0,  1     ]  

   [ right.x, right.y, right.z, -dot(right, eye) ]
 = [ up.x,    up.y,    up.z,    -dot(up,    eye) ]
   [ dir.x,   dir.y,   dir.z,   -dot(dir,   eye) ]
   [ 0,       0,       0,             1          ]
----


=== Matrix-Matrix product

This is how the product of two 4-by-4 matrices is determined:
----
[ a b c d ]   [ A B C D ] 
[ e f g h ] x [ E F G H ] = 
[ i j k l ]   [ I J K L ] 
[ m n o p ]   [ M N O P ] 

[ aA+bE+cI+dM aB+bF+cJ+dN aC+bG+cK+dO aD+bH+cL+dP ] 
[ eA+fE+gI+hM eB+fF+gJ+hN eC+fG+gK+hO eD+fH+gL+hP ] 
[ iA+jE+kI+lM iB+jF+kJ+lN iC+jG+kK+lO iD+jH+kL+lP ] 
[ mA+nE+oI+pM mB+nF+oJ+pN mC+nG+oK+pO mD+nH+oL+pP ] 
----

This is how the product of matrix by vector determined :
----
[ a b c d ]   [ X ]   [ aX + bY + cZ + d*0 ] 
[ e f g h ] x [ Y ] = [ eX + fY + gZ + h*0 ] 
[ i j k l ]   [ Z ]   [ iX + jY + kZ + l*0 ]
[ m n o p ]   [ 0 ]   [         0          ]
----

=== Movement matrix

*M_lookAt* = *M_movement* *** *M_lookAt*

Where M_movement is a translation matrix of movement-vector (movement_x, movement_y, movement_z).
Follow this, we can determine lookAt-matrix like composition with movement:
----
[ 1, 0, 0, movement_x ]   [ right.x, right.y, right.z, -dot(right, eye) ] 
[ 0, 1, 0, movement_y ] * [ up.x,    up.y,    up.z,    -dot(up,    eye) ] =
[ 0, 0, 1, movement_z ]   [ dir.x,   dir.y,   dir.z,   -dot(dir,   eye) ]
[ 0, 0, 0, 1          ]   [ 0,       0,       0,             1          ]

  [ right.x, right.y, right.z, -dot(right, eye) + movement_x ] 
= [ up.x,    up.y,    up.z,    -dot(up,    eye) + movement_y ]
  [ dir.x,   dir.y,   dir.z,   -dot(dir,   eye) + movement_z ]
  [ 0,       0,       0,                     1               ]
----
Each component of vector is movement of separate direction:

* *movement_x* is movement '"left-right"' in camera-space

* *movement_y* is movement '"up-down"' in camera-space

* *movement_z* is movement '"forward-backward"' in camera-space



== LeftHand view 


Transformation vector to Camera view:

V' = Mmv * V = Mrot_back * (Mpos_back * V) = (Mrot_back * Mpos_back) * V

Mmv = (Mrot_back * Mpos_back)

*1)* Transformation  to camera position:

----
 [1 0 0 -Pos.x]
 [0 1 0 -Pos.y] = Mpos_back
 [0 0 1 -Pos.z]
 [0 0 0  1    ]
----

*2)* Transformation to back rotation
Get the basis Matrix frame(Mf):

----
 [vRight.x vUp.x vDir.x 0]
 [vRight.y vUp.y vDir.y 0] = Mf;
 [vRight.z vUp.z vDir.z 0]
 [  0       0      0    1]
----

Get the Matrix of Z-invertion(Mz) for LeftHand coordinate system:

----
 [1 0  0 0]
 [0 1  0 0] = Mz;
 [0 0 -1 0]
 [0 0  0 1]
----

Calculate Matrix frame of Z-invertion(Mf_z):
Mf_z = Mf * Mz;

----
 [vRight.x vUp.x -vDir.x 0]
 [vRight.y vUp.y -vDir.y 0] = Mf_z;
 [vRight.z vUp.z -vDir.z 0]
 [  0       0       0    1]
----

Mf_zback * Mf_z = Midentity

cos(90) = dot(vRight, vUp) = dot(vRight, vDir) = dot(vDir, vUp) = 0
 
----
[ vRight.x  vRight.y  vRight.z 0] [vRight.x vUp.x -vDir.x 0] 
[ vUp.x     vUp.y     vUp.z    0]*[vRight.y vUp.y -vDir.y 0]=
[-vDir.x   -vDir.y   -vDir.z   0] [vRight.z vUp.z -vDir.z 0] 
[ 0         0         0        1] [0        0      0      1] 

  [ dot(vRight, vRight)  dot(vRight, vUp)  dot(vRight, vDir)  0 ]  [1 0 0 0]
= [ dot(vUp,    vRight)  dot(vUp,    vUp)  dot(vUp,    vDir)  0 ] =[0 1 0 0] 
  [ dot(-vDir,  vRight)  dot(-vDir,  vUp)  dot(-vDir, -vDir)  0 ]  [0 0 1 0]
  [ 0                    0                 0                  1 ]  [0 0 0 1]
----

*3)* Final lookAt matrix is: (Mrot_back * Mpos_back) = Mf_zback * Mpos_back:

----
           [ vRight.x vRight.y  vRight.z 0] [1 0 0 -Pos.x]
M_lookAt = [ vUp.x    vUp.y     vUp.z    0]*[0 1 0 -Pos.y] =
           [-vDir.x  -vDir.y   -vDir.z   0] [0 0 1 -Pos.z]
           [ 0        0         0        1] [0 0 0  1    ]
 
  [ vRight.x  vRight.y  vRight.z  -Dot(vRight,Pos) ]
= [ vUp.x     vUp.y     vUp.z     -Dot(vUp,   Pos) ]
  [-vDir.x   -vDir.y   -vDir.z     Dot(vDir,  Pos) ]
  [ 0         0         0          1               ]
----
